name: 'changed-objects'
description: 'Get changed objects'
inputs:
  added:
    description: 'Show added objects'
    required: false
    default: 'false'
  deleted:
    description: 'Show deleted objects'
    required: false
    default: 'false'
  modified:
    description: 'Show modified objects'
    required: false
    default: 'false'
  default_branch:
    description: 'Set default branch'
    required: false
    default: 'main'
  merge_base:
    description: 'Set merge-base revision name'
    required: false
    default: ''
  ignore:
    description: 'A newline separated list of ignored cases'
    required: false
    default: ''
  group_by:
    description: 'Show changed objects by given directory unit'
    required: false
    default: ''
  dir_exist:
    description: 'Filter objects by state of dir existing'
    required: false
    default: 'all'
  directories:
    description: 'Specify directories to pass changed-objects command'
    required: false
    default: ''
outputs:
  changes:
    description: 'Changed objects'
  nothing:
    description: 'True if no changes returned'
runs:
  using: 'docker'
  image: 'Dockerfile'
