name: 'changed-objects'
description: 'Get changed objects'
inputs:
  added:
    description: 'Show added objects'
    required: false
    default: 'false'
  deleted:
    description: 'Show deleted objects'
    required: false
    default: 'false'
  modified:
    description: 'Show modified objects'
    required: false
    default: 'false'
  dirname:
    description: 'Return the result with each directory name'
    required: false
    default: 'false'
  output:
    description: 'Set output format'
    required: false
    default: ''
  default-branch:
    description: 'Set default branch'
    required: false
    default: 'main'
outputs:
  changed:
    description: 'Changed objects'
runs:
  using: 'docker'
  image: 'Dockerfile'
